// Country configuration for branch pages
export const countryConfig: Record<string, {
  registrationAuthority: string;
  registrationFee: string;
  processingTime: string;
  notaryRequired: boolean;
  heroDescription: string;
  price: string;
}> = {
  france: {
    registrationAuthority: 'RCS (Registre du Commerce et des Sociétés)',
    registrationFee: '€150 registration fee',
    processingTime: '7-10 business days',
    notaryRequired: false,
    heroDescription: "France is one of Europe's largest economies and a key market for international business. Your French Branch Office gives your business instant credibility in the EU market.",
    price: '€1,495',
  },
  spain: {
    registrationAuthority: 'Registro Mercantil (Commercial Registry)',
    registrationFee: '€150 registration fee',
    processingTime: '7-10 business days',
    notaryRequired: true,
    heroDescription: 'Spain offers access to the Iberian Peninsula and strong connections to Latin American markets. Your Spanish Branch Office gives your business instant credibility in the EU market.',
    price: '€1,495',
  },
  italy: {
    registrationAuthority: 'Registro delle Imprese (Business Register)',
    registrationFee: '€150 registration fee',
    processingTime: '7-10 business days',
    notaryRequired: true,
    heroDescription: "Italy is one of Europe's largest economies and a gateway to Mediterranean markets. Your Italian Branch Office gives your business instant credibility in the EU market.",
    price: '€1,495',
  },
  poland: {
    registrationAuthority: 'KRS (National Court Register)',
    registrationFee: '€100 registration fee',
    processingTime: '7-10 business days',
    notaryRequired: true,
    heroDescription: "Poland is Central Europe's largest economy and a gateway to Eastern European markets. Your Polish Branch Office gives your business instant credibility in the EU market.",
    price: '€1,495',
  },
  austria: {
    registrationAuthority: 'Firmenbuch (Company Register)',
    registrationFee: '€100 registration fee',
    processingTime: '7-10 business days',
    notaryRequired: true,
    heroDescription: 'Austria offers excellent access to Central and Eastern European markets with a stable business environment. Your Austrian Branch Office gives your business instant credibility in the EU market.',
    price: '€1,495',
  },
  bulgaria: {
    registrationAuthority: 'Commercial Register',
    registrationFee: '€100 registration fee',
    processingTime: '7-10 business days',
    notaryRequired: false,
    heroDescription: 'Bulgaria offers competitive costs and access to Eastern European markets. Your Bulgarian Branch Office gives your business instant credibility in the EU market.',
    price: '€1,495',
  },
  croatia: {
    registrationAuthority: 'Court Register',
    registrationFee: '€100 registration fee',
    processingTime: '7-10 business days',
    notaryRequired: true,
    heroDescription: 'Croatia offers access to the Adriatic region and growing Balkan markets. Your Croatian Branch Office gives your business instant credibility in the EU market.',
    price: '€1,495',
  },
  cyprus: {
    registrationAuthority: 'Department of Registrar of Companies',
    registrationFee: '€100 registration fee',
    processingTime: '7-10 business days',
    notaryRequired: false,
    heroDescription: 'Cyprus offers strategic access to Middle Eastern and Eastern European markets with favorable tax conditions. Your Cypriot Branch Office gives your business instant credibility in the EU market.',
    price: '€1,495',
  },
  czechrepublic: {
    registrationAuthority: 'Commercial Register',
    registrationFee: '€100 registration fee',
    processingTime: '7-10 business days',
    notaryRequired: true,
    heroDescription: 'The Czech Republic offers excellent access to Central European markets with a skilled workforce. Your Czech Branch Office gives your business instant credibility in the EU market.',
    price: '€1,495',
  },
  denmark: {
    registrationAuthority: 'CVR (Central Business Register)',
    registrationFee: '€100 registration fee',
    processingTime: '5-7 business days',
    notaryRequired: false,
    heroDescription: 'Denmark offers excellent business infrastructure and access to Nordic markets. Your Danish Branch Office gives your business instant credibility in the EU market.',
    price: '€1,495',
  },
  estonia: {
    registrationAuthority: 'Commercial Register',
    registrationFee: '€100 registration fee',
    processingTime: '5-7 business days',
    notaryRequired: false,
    heroDescription: 'Estonia offers a fully digital business environment and access to Baltic and Nordic markets. Your Estonian Branch Office gives your business instant credibility in the EU market.',
    price: '€1,495',
  },
  finland: {
    registrationAuthority: 'Trade Register',
    registrationFee: '€100 registration fee',
    processingTime: '7-10 business days',
    notaryRequired: false,
    heroDescription: 'Finland offers excellent business infrastructure and access to Nordic and Russian markets. Your Finnish Branch Office gives your business instant credibility in the EU market.',
    price: '€1,495',
  },
  greece: {
    registrationAuthority: 'GEMI (General Commercial Registry)',
    registrationFee: '€100 registration fee',
    processingTime: '7-10 business days',
    notaryRequired: true,
    heroDescription: 'Greece offers strategic access to Mediterranean and Balkan markets. Your Greek Branch Office gives your business instant credibility in the EU market.',
    price: '€1,495',
  },
  hungary: {
    registrationAuthority: 'Company Registry',
    registrationFee: '€100 registration fee',
    processingTime: '7-10 business days',
    notaryRequired: true,
    heroDescription: 'Hungary offers competitive costs and access to Central European markets. Your Hungarian Branch Office gives your business instant credibility in the EU market.',
    price: '€1,495',
  },
  ireland: {
    registrationAuthority: 'CRO (Companies Registration Office)',
    registrationFee: '€100 registration fee',
    processingTime: '5-7 business days',
    notaryRequired: false,
    heroDescription: 'Ireland offers excellent access to English-speaking markets and favorable tax conditions. Your Irish Branch Office gives your business instant credibility in the EU market.',
    price: '€1,495',
  },
  latvia: {
    registrationAuthority: 'Commercial Register',
    registrationFee: '€100 registration fee',
    processingTime: '7-10 business days',
    notaryRequired: false,
    heroDescription: 'Latvia offers access to Baltic markets and growing connections to Eastern Europe. Your Latvian Branch Office gives your business instant credibility in the EU market.',
    price: '€1,495',
  },
  lithuania: {
    registrationAuthority: 'Centre of Registers',
    registrationFee: '€100 registration fee',
    processingTime: '7-10 business days',
    notaryRequired: false,
    heroDescription: 'Lithuania offers access to Baltic markets and growing tech sector. Your Lithuanian Branch Office gives your business instant credibility in the EU market.',
    price: '€1,495',
  },
  luxembourg: {
    registrationAuthority: 'RCS (Registre de Commerce et des Sociétés)',
    registrationFee: '€100 registration fee',
    processingTime: '5-7 business days',
    notaryRequired: true,
    heroDescription: 'Luxembourg offers excellent financial services infrastructure and access to European markets. Your Luxembourg Branch Office gives your business instant credibility in the EU market.',
    price: '€1,495',
  },
  malta: {
    registrationAuthority: 'MFSA (Malta Financial Services Authority)',
    registrationFee: '€100 registration fee',
    processingTime: '7-10 business days',
    notaryRequired: true,
    heroDescription: 'Malta offers strategic access to Mediterranean markets and favorable tax conditions. Your Maltese Branch Office gives your business instant credibility in the EU market.',
    price: '€1,495',
  },
  portugal: {
    registrationAuthority: 'Commercial Registry',
    registrationFee: '€100 registration fee',
    processingTime: '7-10 business days',
    notaryRequired: true,
    heroDescription: 'Portugal offers access to the Iberian Peninsula and strong connections to Portuguese-speaking markets. Your Portuguese Branch Office gives your business instant credibility in the EU market.',
    price: '€1,495',
  },
  romania: {
    registrationAuthority: 'Trade Register',
    registrationFee: '€100 registration fee',
    processingTime: '7-10 business days',
    notaryRequired: false,
    heroDescription: 'Romania offers competitive costs and access to Eastern European markets. Your Romanian Branch Office gives your business instant credibility in the EU market.',
    price: '€1,495',
  },
  slovakia: {
    registrationAuthority: 'Commercial Register',
    registrationFee: '€100 registration fee',
    processingTime: '7-10 business days',
    notaryRequired: true,
    heroDescription: 'Slovakia offers competitive costs and access to Central European markets. Your Slovak Branch Office gives your business instant credibility in the EU market.',
    price: '€1,495',
  },
  slovenia: {
    registrationAuthority: 'AJPES (Agency of the Republic of Slovenia for Public Legal Records)',
    registrationFee: '€100 registration fee',
    processingTime: '7-10 business days',
    notaryRequired: true,
    heroDescription: 'Slovenia offers access to Central European markets and excellent infrastructure. Your Slovenian Branch Office gives your business instant credibility in the EU market.',
    price: '€1,495',
  },
  sweden: {
    registrationAuthority: 'Bolagsverket (Swedish Companies Registration Office)',
    registrationFee: '€100 registration fee',
    processingTime: '7-10 business days',
    notaryRequired: false,
    heroDescription: 'Sweden offers excellent business infrastructure and access to Nordic markets. Your Swedish Branch Office gives your business instant credibility in the EU market.',
    price: '€1,495',
  },
};


