import {
  BuildingIcon,
  FileTextIcon,
  UsersIcon,
  ShieldCheckIcon,
} from 'lucide-react';

export function getServiceDetails(countryName: string, registrationAuthority: string) {
  return {
    branch: {
      id: 'branch',
      name: 'Company Registration',
      icon: <BuildingIcon className="h-6 w-6" />,
      shortDescription: `Complete ${registrationAuthority} registration and legal entity setup`,
      fullDescription: `Full legal entity establishment with ${registrationAuthority} registration, commercial register extract, and all necessary documentation for operating in ${countryName}.`,
      benefits: [
        `Official ${registrationAuthority} registration`,
        `${countryName} commercial register extract`,
        'Corporate documents preparation',
        'Legal address provision',
        'No notary requirement',
        'Fast processing',
      ],
      process: [
        'Document collection and verification',
        `Application submission to ${registrationAuthority}`,
        'Registration with business registry',
        'Commercial register extract issuance',
        'Final documentation delivery',
      ],
      timeline: '5-10 business days',
      included: true,
    },
    vat: {
      id: 'vat',
      name: 'VAT & Tax Setup',
      icon: <FileTextIcon className="h-6 w-6" />,
      shortDescription: `${countryName} tax number and EU VAT registration`,
      fullDescription: `Complete VAT registration with ${countryName} tax authorities, including EU VAT number acquisition for intra-community transactions.`,
      benefits: [
        `${countryName} tax number registration`,
        'EU VAT number acquisition',
        'Tax authority registration',
        'Quarterly VAT return setup',
        'Compliance monitoring',
        'Intrastat reporting setup',
      ],
      process: [
        'Tax registration application',
        'VAT number acquisition',
        'Tax ID number issuance',
        'Accounting system setup',
        'First return preparation',
        'Ongoing compliance support',
      ],
      timeline: '1-2 weeks',
      included: true,
    },
    employer: {
      id: 'employer',
      name: 'Employer Services',
      icon: <UsersIcon className="h-6 w-6" />,
      shortDescription: `Hire employees and manage payroll in ${countryName}`,
      fullDescription: `Complete employer registration with ${countryName} authorities and payroll infrastructure to hire and manage employees compliantly.`,
      benefits: [
        'Employer registration',
        'Social security setup',
        'Employment contract templates',
        'Payroll infrastructure',
        'Employee onboarding support',
        `${countryName} labor law compliance`,
      ],
      process: [
        'Employer registration filing',
        'Social security enrollment',
        'Payroll system setup',
        'Contract template creation',
        'First employee onboarding',
        'Ongoing payroll support',
      ],
      timeline: '1-2 weeks',
      included: true,
    },
    compliance: {
      id: 'compliance',
      name: 'Ongoing Compliance',
      icon: <ShieldCheckIcon className="h-6 w-6" />,
      shortDescription: 'Automated compliance monitoring and management',
      fullDescription: `Comprehensive compliance management system that monitors deadlines, regulatory changes, and ensures your ${countryName} branch stays compliant.`,
      benefits: [
        'Real-time compliance tracking',
        'Automated deadline alerts',
        'Regulatory update notifications',
        'Annual report automation',
        'Document management system',
        '24/7 portal access',
      ],
      process: [
        'Compliance calendar setup',
        'Automated alert configuration',
        'Document repository creation',
        'Ongoing monitoring activation',
        'Regular compliance reviews',
        'Annual reporting support',
      ],
      timeline: 'Immediate',
      included: true,
    },
  };
}

// Country flags mapping
export const countryFlags: Record<string, string> = {
  belgium: '🇧🇪',
  germany: '🇩🇪',
  france: '🇫🇷',
  spain: '🇪🇸',
  italy: '🇮🇹',
  poland: '🇵🇱',
  austria: '🇦🇹',
  bulgaria: '🇧🇬',
  croatia: '🇭🇷',
  cyprus: '🇨🇾',
  czechrepublic: '🇨🇿',
  denmark: '🇩🇰',
  estonia: '🇪🇪',
  finland: '🇫🇮',
  greece: '🇬🇷',
  hungary: '🇭🇺',
  ireland: '🇮🇪',
  latvia: '🇱🇻',
  lithuania: '🇱🇹',
  luxembourg: '🇱🇺',
  malta: '🇲🇹',
  portugal: '🇵🇹',
  romania: '🇷🇴',
  slovakia: '🇸🇰',
  slovenia: '🇸🇮',
  sweden: '🇸🇪',
};


